<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOZs1D8z\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOZs1D8z/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOZs1D8z.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOZs1D8z\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOZs1D8z\App_KernelProdContainer([
    'container.build_hash' => 'OZs1D8z',
    'container.build_id' => 'fb745990',
    'container.build_time' => 1616345295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOZs1D8z');
