<?php

namespace Container76K5MyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MTCLXzRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MTCLXzR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MTCLXzR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'task' => ['privates', '.errored..service_locator.MTCLXzR.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.MTCLXzR": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'em' => '?',
            'task' => 'App\\Entity\\Task',
        ]);
    }
}
