<?php

namespace Container7pYITcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HJCqGfUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hJCqGfU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hJCqGfU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'task' => ['privates', '.errored..service_locator.hJCqGfU.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.hJCqGfU": it references class "App\\Entity\\Task" but no such service exists.'],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'em' => '?',
            'task' => 'App\\Entity\\Task',
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
