<?php

namespace Container7pYITcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SgRUSsbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sgRUSsb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sgRUSsb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notifierService' => ['privates', 'App\\Service\\NotifierService', 'getNotifierServiceService', true],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'em' => '?',
            'notifierService' => 'App\\Service\\NotifierService',
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
