<?php

namespace Container7pYITcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifierServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NotifierService' shared autowired service.
     *
     * @return \App\Service\NotifierService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NotifierService.php';

        return $container->privates['App\\Service\\NotifierService'] = new \App\Service\NotifierService();
    }
}
